#!/bin/bash

set -euo pipefail

log() {
    printf "[%s] %s\n" "$(date)" "$@"
}

if [ ! -d /var/racksnaps ]; then
    log "Creating /var/racksnaps..."
    sudo mkdir -p /var/racksnaps/{cache,snapshots,built-snapshots,store}
    sudo chown -R racksnaps:racksnaps /var/racksnaps
fi

if [ ! -L /var/www/snapshots ]; then
    log "Linking snapshots to www..."
    ln -s /var/racksnaps/snapshots /var/www/snapshots
fi

# For backwards compatibility.  Points to regular snapshots.
if [ ! -L /var/www/built-snapshots ]; then
    log "Linking built-snapshots to www..."
    ln -s /var/racksnaps/built-snapshots /var/www/snapshots
fi

log "Reloading nginx config..."
service nginx reload

log "Pulling docker images..."
docker pull bogdanp/racksnaps:8.5
docker pull bogdanp/racksnaps-built:8.5

log "Pruning docker containers & images..."
docker container prune -f
docker image prune -f

log "Reloading systemd daemon..."
systemctl daemon-reload

log "Restarting site service..."
service racksnaps-site restart
