name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * MON"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test one package
      run: ./test.sh component-lib
